markdown: rdiscount
pygments: true
permalink: /:categories/:year/:month/:day/:title
rdiscount:
  extensions: [smart]

url: http://mmucs.co.uk
name: MMU Computing Society
twitter: mmucompsoc
github: mmucomputing
facebook: mmucomputingsociety

authors:
  jimmy:
    name: Jimmy Thompson
    image: http://www.gravatar.com/avatar/73083e7e6bda1576bf6ea9e5be037c78.jpg?s=110
    twitter: jimmythompson
    github: jimmythompson
    bio: "Jimmy is a final year student at MMU and ex-Chairman of the Computing Society. Living in Manchester, when not studying he works on open source projects on Github, as well as trying to destroy the world using Python or Go."
  libbie:
    name: Elizabeth Chesters
    image: http://www.gravatar.com/avatar/b7c1857e4f8de66bd7a42a5cf7f5722f.jpg?s=110
    twitter: echesters
    github: liloka
    bio: "Smelly."
  ben:
    name: Benjamin Dale
    image: http://www.gravatar.com/avatar/f36fa5e0a0c085b16923daeee2286c5e.png?s=110
    twitter: mrbenjamind
    github: ben-dale
    bio: "Ben is a final year student at MMU and current Chairman of the Computing Society."
