markdown: rdiscount
pygments: true
permalink: :title
rdiscount:
  extensions: [smart]

url: http://mmucs.co.uk
name: MMU Computing Society
twitter: mmucomputing
github: mmucomputing

authors:
  jimmy:
    name: Jimmy Thompson
    image: http://www.gravatar.com/avatar/73083e7e6bda1576bf6ea9e5be037c78.jpg
    twitter: jimmythompson
    github: jimmythompson
    bio: "Jimmy is a final year student at MMU and Chairman of the Computing Society. Living in Manchester, when not studying he works on open source projects on Github, as well as tries to destroy the world using Python or Go."
  libbie:
    name: Elizabeth Chesters
    image: http://www.gravatar.com/avatar/b7c1857e4f8de66bd7a42a5cf7f5722f.jpg
    twitter: echesters
    github: liloka
    bio: "Smelly."